### ISSUE TITLE
Post excerpt size issue

### ISSUE THREAD

**Issue by chopraaa** [onweru/hugo-swift-theme#12]
This is what the post looks like on a new installation:

![image](https://user-images.githubusercontent.com/360979/61147497-17d31700-a4fa-11e9-847e-c44aa20161fa.png)

Excerpt is in the center of the page (should be ideally on the left) and is not 100% width.

**Comment by onweru** [comment]
@chopraaa, thanks for bringing this to my attention. I will explore the bug and apply a fix asap.
