### ISSUE TITLE
HUGO-SWIFT-THEME theme does not support Hugo version 0.51. Minimum version required is 0.55

### ISSUE THREAD

**Issue by yezihack** [onweru/hugo-swift-theme#18]
ERROR 2019/08/06 16:58:15 HUGO-SWIFT-THEME theme does not support Hugo version 0.51. Minimum version required is 0.55
Total in 91 ms
Error: Error building site: logged 1 error(s)

**Comment by onweru** [comment]
@yezihack, I’ll bump the minimum required version down. My bad, I overlooked that someone might be using an older version of Hugo.

Thanks for raising this issue.
