### ISSUE TITLE
Sine wave display problem

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#19]
# Steps to reproduce
1. Click on the demo link shown on the top of this repo with Firefox.
2. Observe the error described in the title.

# Screenshot
![Firefox recording of this theme](https://user-images.githubusercontent.com/5748535/62536085-589a2380-b84d-11e9-9b84-19b3fa066b69.gif)

# Expected behavior
![expected](https://user-images.githubusercontent.com/5748535/62536256-d1997b00-b84d-11e9-96c7-d22a54aad3e3.gif)

# Versions concerned
- OS: Ubuntu 18.04
- Browser: Firefox 68.0.1 (64-bit)

:thinking: I think this might concern Firefox on other platforms as well.

**Comment by onweru** [comment]
@VincentTam, please let me know if this issue is still occurring? I haven't had the opportunity to test it. I'm on a macOS beta, Mozilla was acting up last week. Let me check

**Comment by VincentTam** [comment]
Yes, this issue still concerns (X)Ubuntu 18.04 installed on my :computer:.

**Comment by onweru** [comment]
@VincentTam, I finally got firefox to macOS Catalina. I confirmed that the bug was in fact present even on macOS. I have deployed a fix that works for me. Please confirm if it does on yours.

**Comment by VincentTam** [comment]
Thanks this worked.

![out](https://user-images.githubusercontent.com/5748535/63642487-04ea5f80-c6c0-11e9-8607-d479f8e456f4.gif)

Please use `git pull --rebase` next time to keep Git history down.

**Comment by onweru** [comment]
> Please use git pull --rebase next time to keep Git history down.

updating my git aliases 🏃

**Comment by VincentTam** [comment]
> > Please use git pull --rebase next time to keep Git history down.
> 
> updating my git aliases

You may use [oh my Zsh](https://ohmyz.sh/), which comes with an array of [convenient aliases](https://github.com/robbyrussell/oh-my-zsh/blob/d6fc6edb29a0dc9c91b8a1ad7b4db4c235420b08/plugins/git/README.md).
