### ISSUE TITLE
Staticman instructions

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#2]
Hi, this is the maintainer of @staticmanlab, a [public GitLab instance](https://gitlab.com/staticmanlab) of Staticman API.

In README, it's written

> Then proceed to setup staticman in **staticman.yml**. See the example site and the [staticman docs](https://staticman.net/docs/) for reference.

According to the documentation, Staticman can only recognise root-level `staticman.yml`.  Nonetheless, in the example site, you've put `staticman.yml` under the folder `/data`, and these settings are referenced in the layouts `{{ .Site.Data.staticman }}`.   It would be nice if you make  the role of these config files clear.  Btw, Staticman's settings have to be split into two files:

1. repo config: the path must be `/staticman.yml`
2. site config: usually `/config.toml`, but it can be elsewhere.

**Comment by onweru** [comment]
Forgive me for not be being thorough, the instructions you listed above are in fact true. Here is how I implemented the same. 
<img width="1280" alt="Screen Shot 2019-05-19 at 5 25 47 PM" src="https://user-images.githubusercontent.com/16350351/57983584-54cfdf80-7a5c-11e9-96da-6e9f2e85b8eb.png">

Note that there are two statesman.yml files. One on the root level and one inside the data directory. Their contents are different.

**Comment by VincentTam** [comment]
Would you mind including your root-level `staticman.yml` into the project (like other themes do) so that interested users _won't_ have to type all this by hand?

**Comment by VincentTam** [comment]
Thanks for publishing the config YML file.  Sorry to be meticulous, but https://github.com/onweru/hugo-swift-theme/commit/80447c6ecaee487e2038acdb2129370d9bab84d2#diff-04c6e90faac2675aa89e2176d2eec7d8 is insufficient and contains a circular reference.

- README line 52: view example site config
- example site config line 9: See README https://github.com/onweru/hugo-swift-theme/blob/df4bcb15dae039f7880b1997488bb6c8a7b5238f/exampleSite/config.toml#L8-L9

The reference to the Staticman's project would help, but there're some parameters in your Go template file quite specific to your theme that your theme's Git repo is the only appropriate place to document them.

https://github.com/onweru/hugo-swift-theme/blob/69541d134cd236e8c2e5fdf6c0f91bfbeebed32c/layouts/partials/comments-form.html#L1-L3

You've done a great job in publishing your `staticman.yml`, but the naming of the config files `staticman.yml` and `data/staticman.yml` would possibly confuse normal bloggers who _don't_ know the internal structure of your theme.  In the linked git diff, you've referred the ambiguity of your instructions to the ongoing development of Staticman.  Nonetheless, the former has _nothing_ to do with the later.  Usually, the site config for commenting services are put in a root-level config file, so that users can identify them easily.  You can make it clear by either

1. adding a sample config file with commented explanations, for example [Beautiful Jekyll's config](https://github.com/daattali/beautiful-jekyll/blob/58e8f7db85786a147cf9f42223095e77281330e4/_config.yml#L124-L149).
2. documenting the parameters in your template code in the README section, or a web site, like Staticman's web site, which documents it's API parameters.  I remark that that's outdated due to the launch of v3 though.

Now, I'll move on verifying whether #4 has been resolved.

**Comment by onweru** [comment]
> Thanks for publishing the config YML file. Sorry to be meticulous, but [80447c6#diff-04c6e90faac2675aa89e2176d2eec7d8](https://github.com/onweru/hugo-swift-theme/commit/80447c6ecaee487e2038acdb2129370d9bab84d2#diff-04c6e90faac2675aa89e2176d2eec7d8) is insufficient and contains a circular reference.
> 
> * README line 52: view example site config
> * example site config line 9: See README https://github.com/onweru/hugo-swift-theme/blob/df4bcb15dae039f7880b1997488bb6c8a7b5238f/exampleSite/config.toml#L8-L9
> 
> The reference to the Staticman's project would help, but there're some parameters in your Go template file quite specific to your theme that your theme's Git repo is the only appropriate place to document them.
> 
> https://github.com/onweru/hugo-swift-theme/blob/69541d134cd236e8c2e5fdf6c0f91bfbeebed32c/layouts/partials/comments-form.html#L1-L3
> 
> You've done a great job in publishing your `staticman.yml`, but the naming of the config files `staticman.yml` and `data/staticman.yml` would possibly confuse normal bloggers who _don't_ know the internal structure of your theme. In the linked git diff, you've referred the ambiguity of your instructions to the ongoing development of Staticman. Nonetheless, the former has _nothing_ to do with the later. Usually, the site config for commenting services are put in a root-level config file, so that users can identify them easily. You can make it clear by either
> 
> 1. adding a sample config file with commented explanations, for example [Beautiful Jekyll's config](https://github.com/daattali/beautiful-jekyll/blob/58e8f7db85786a147cf9f42223095e77281330e4/_config.yml#L124-L149).
> 2. documenting the parameters in your template code in the README section, or a web site, like Staticman's web site, which documents it's API parameters.  I remark that that's outdated due to the launch of v3 though.
> 
> Now, I'll move on verifying whether #4 has been resolved.

@VincentTam, time is my main constraint, I would love to explore your suggestions but it's likely I won't be able to get into that soon. Would you like me to add you as a collaborator on the project?

**Comment by VincentTam** [comment]
Thanks for your invitation.  Yes, please.

**Comment by onweru** [comment]
> Thanks for your invitation. Yes, please.

Done. Thanks for contributing Vincent.

**Comment by VincentTam** [comment]
Suggestions done in #6.  The sample config files now contain instructive comments for Staticman's settings.
