### ISSUE TITLE
Compilation warning:  Data for key .... overridden ...

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#3]
Steps to reproduce the error:

```
$ git remote -v
origin	git@framagit.org:staticman-gitlab-pages/hugo-swift-theme.git (fetch)
origin	git@framagit.org:staticman-gitlab-pages/hugo-swift-theme.git (push)
upstream	https://github.com/onweru/hugo-swift-theme.git (fetch)
upstream	https://github.com/onweru/hugo-swift-theme.git (push)
$ git fetch upstream master
$ git checkout upstream/master
$ hugo --themesDir=../.. -d ../public
Building sites … WARN 2019/05/19 10:06:43 Data for key 'name' in path 'hugo-swift-theme/designer.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:06:43 Data for key 'url' in path 'hugo-swift-theme/designer.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:06:43 The []interface {} data from 'hugo-swift-theme/menu.yml' overridden by higher precedence []interface {} data already in the data tree
WARN 2019/05/19 10:06:43 Data for key 'repository' in path 'hugo-swift-theme/staticman.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:06:43 Data for key 'endpoint' in path 'hugo-swift-theme/staticman.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:06:43 Data for key 'branch' in path 'hugo-swift-theme/staticman.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:06:43 Data for key 'username' in path 'hugo-swift-theme/staticman.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:06:43 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.

                   | EN  
+------------------+----+
  Pages            | 30  
  Paginator pages  |  2  
  Non-page files   |  0  
  Static files     | 37  
  Processed images |  0  
  Aliases          | 12  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 266 ms
```

**Comment by VincentTam** [comment]
Status update:

After f8bbcdc & c2fad69 and the linked PR, the number of warnings have been reduced by half.  You may refer to GitLab's CI output: https://framagit.org/staticman-gitlab-pages/hugo-swift-theme/-/jobs/412425

**Comment by onweru** [comment]
> https://framagit.org/staticman-gitlab-pages/hugo-swift-theme/-/jobs/412425

Awesome. 

I observed that you're using an docker Image in your gitlab-ci.yml file that works with Hugo-extended. Is it self-hosted?

**Comment by VincentTam** [comment]
> I observed that you're using an docker Image in your gitlab-ci.yml file that works with Hugo-extended. Is it self-hosted?

I don't even know Docker, so it's impossible to self-host one.  In fact, this is copied from [Hugo's doc for hosting on GitLab](https://gohugo.io/hosting-and-deployment/hosting-on-gitlab/#readout).

**Comment by onweru** [comment]
> > I observed that you're using an docker Image in your gitlab-ci.yml file that works with Hugo-extended. Is it self-hosted?
> 
> I don't even know Docker, so it's impossible to self-host one. In fact, this is adapted from [Hugo's doc for hosting on GitLab](https://gohugo.io/hosting-and-deployment/hosting-on-gitlab/#readout).
> 
> P.S. It's much simpler to host Hugo on GitLab than on GitHub.

It was hiding in plain site, huh :) ... thanks.

**Comment by VincentTam** [comment]
Thanks for your attempt to fix this issue, but the removal of `data/*.yml/` would cause a compilation error due to instances of `.Site.Data.authors`, `.Site.Data.designer` in your theme.
https://github.com/onweru/hugo-swift-theme/blob/31d40fd361d754aca840eceaeec266e2bf6ec7b8/layouts/partials/footer.html#L1-L5
https://github.com/onweru/hugo-swift-theme/blob/f8bbcdc42e10124f8f1c2abdfc98af51e529ce85/layouts/partials/menu.html#L2-L7
https://github.com/onweru/hugo-swift-theme/blob/495c69ccbf5b555d660d8642be61032f073bda1c/layouts/_default/single.html#L6

**Comment by onweru** [comment]
@VincentTam, I'm not sure that there would be any compilation errors since the exampleSite contains the relevant data files. You're supposed to use the exampleSite for as the start or for reference.

**Comment by VincentTam** [comment]
> @VincentTam, I'm not sure that there would be any compilation errors since the exampleSite contains the relevant data files. You're supposed to use the exampleSite for as the start or for reference.

Sorry my bad!  The [compilation](https://framagit.org/staticman-gitlab-pages/hugo-swift-theme/-/jobs/417828) went smooth.  Thanks for great work!
