### ISSUE TITLE
What is the role of the 2nd argument in this function?

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#30]
In https://github.com/onweru/hugo-swift-theme/blob/74aa154158cd290bf49f9be73a01b885e5219cef/assets/js/index.js#L5-L8, `parent` is never used.  Perhaps there's a mistake.

**Comment by onweru** [comment]
I used `parent` purposely for a scenario where you need to be more specific. That is, in a scenario where you want to query from a different node other than the `document`. 

For example, we could have:

```javascript
let parent, child, greatGrandChild;
parent = document.querySelector('.parent');
// search for list items within the parent node. They could be nested several levels deep
greatGrandChild = parent.querySelector('li');
```

As you may have noticed, `parent` is set to *document* by default. Thusly, it's optional.

**Comment by onweru** [comment]
> I used `parent` purposely for a scenario where you need to be more specific. That is, in a scenario where you want to query from a different node other than the `document`.
> 
> For example, we could have:
> 
> ```js
> let parent, child, greatGrandChild;
> parent = document.querySelector('.parent');
> // search for list items within the parent node. They could be nested several levels deep
> greatGrandChild = parent.querySelector('li');
> ```
> 
> As you may have noticed, `parent` is set to _document_ by default. Thusly, it's optional.
> 
> I was trying to replicate the `.find()` function in jQuery. I believe it uses the same principle.

You're right, there's a slight mistake. Thanks for bringing it to my attention
