### ISSUE TITLE
Missing class in Staticman comments?

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#32]
Searching "gravatar" in this repo gives [four results](https://github.com/onweru/hugo-swift-theme/search?q=gravatar&unscoped_q=gravatar), 3 SCSS and 1 HTML file.  In the Go-HTML template, there's no instance of `gravatar` as a class name.
https://github.com/onweru/hugo-swift-theme/blob/f990880aee6e807b308094138c8686c8051af871/layouts/partials/comments.html#L9
Perhaps the class name `gravatar` should be added back?

**Comment by onweru** [comment]
I renamed the `gravatar` class to something else ; I believe `author_pic` in the last refactor. I wasn't quite thorough. Just like #25, I'm still considering how to move forward with everything.

**Comment by onweru** [comment]
> I renamed the `gravatar` class to something else ; I believe `author_pic` in the last refactor. I wasn't quite thorough. Just like #25, I'm still considering how to move forward with everything.

The renaming was to enable me to reuse part of the scss code. You will notice that the `author` & `comment` components share a lot of styles.

While there are more elegant ways achieving the same (e.g sass **mixins or extends**), *programmers tend to be lazy* 😄. That joke is quite true in my case.

**Comment by VincentTam** [comment]
Thanks for clarifications.  Let's drop the "add back `class="gravatar"`" question because I agree with your last paragraph. :smile:
