### ISSUE TITLE
Modal close button doesn't work

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#33]
The line `containsClass(body, show) ? closeModal() : false;` is only executed once on page load.  In that process, the conditional is evaluated to false, so the `closeModal()` is _never_ called.

https://github.com/onweru/hugo-swift-theme/blob/74aa154158cd290bf49f9be73a01b885e5219cef/assets/js/index.js#L183-L200

I'm working on the project for nested comments, which would add about a hundred lines into the JS.  Upon its release, the problem would be fixed.  I'm leaving an issue here for record.

**Comment by onweru** [comment]
True, I will refactor this. Have you been working on this file? I don't want to deal with merge conflicts hehe

**Comment by VincentTam** [comment]
> Have you been working on this file?

I've already found a solution: `closeModal()` contains the listener for the modal close button, so I've added this listener to the browser only when `showModal(...msg)` is invoked.

**Comment by VincentTam** [comment]
Closed via #36.
