### ISSUE TITLE
Deep links null target

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#34]
![Screenshot from 2019-08-13 10-11-07](https://user-images.githubusercontent.com/5748535/62925999-d319f480-bdb3-11e9-9812-6538820ac8d0.png)
![Screenshot from 2019-08-13 10-11-23](https://user-images.githubusercontent.com/5748535/62925987-cb5a5000-bdb3-11e9-8c6e-ff34bc6d8051.png)

https://github.com/onweru/hugo-swift-theme/blob/ed96cfa91ba3fbd5d8363ac5a79dc35e1db75f1f/assets/js/index.js#L297-L311

Should the existence of target be checked first, like this?

```js
// Get the element, add a click listener...
document.getElementById("parent-list").addEventListener("click", function(e) {
	// e.target is the clicked element!
	// If it was a list item
	if(e.target && e.target.nodeName == "LI") {
		// List item found!  Output the ID!
		console.log("List item ", e.target.id.replace("post-", ""), " was clicked!");
	}
});
```

source: https://davidwalsh.name/event-delegate

**Comment by onweru** [comment]
There is an error on line 298 ... there is a missing argument. The deep links function is only supposed to target headings i.e H1 ... H6

**Comment by VincentTam** [comment]
In this case, feel free to edit this part.  I'm working on the part of Staticman.
