### ISSUE TITLE
Post thumbnail display broken on Hugo Themes demo

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#37]
![Screenshot_2019-08-14_15-54-43](https://user-images.githubusercontent.com/5748535/63026747-03dd5500-beac-11e9-9ec9-934595728fa0.png)

https://themes.gohugo.io/theme/hugo-swift-theme

**Comment by onweru** [comment]
I have noticed this for a while now. For some reason `.Params.image` isn't resolved on the demo (check source).

**Comment by onweru** [comment]
@VincentTam, have you noticed the following about the [theme's demo](https://themes.gohugo.io/theme/hugo-swift-theme/):

1. There are post duplicates
2. The demo doesn't read from the [exampleSite directory of this theme](https://github.com/onweru/hugo-swift-theme/tree/master/exampleSite). For instance, if you look closely, you won't find an article titled `emoji support` anywhere in the aforementioned directory 🤔 

If the above observation are in fact true:

* I cannot immediately explain (1) above
* (2) above would explain why the image thumbnails are broken on the demo.

**Comment by onweru** [comment]
> @VincentTam, have you noticed the following about the [theme's demo](https://themes.gohugo.io/theme/hugo-swift-theme/):
> 
> 1. There are post duplicates
> 2. The demo doesn't read from the [exampleSite directory of this theme](https://github.com/onweru/hugo-swift-theme/tree/master/exampleSite). For instance, if you look closely, you won't find an article titled `emoji support` anywhere in the aforementioned directory 🤔
> 
> If the above observation are in fact true:
> 
> * I cannot immediately explain (1) above
> * (2) above would explain why the image thumbnails are broken on the demo.

Aha, it's [all explained here](https://gohugo.io/contribute/themes/). Specifically in this paragraph

> If your theme doesn’t fit into the `Hugo Basic Example` site, we encourage theme authors to supply a self-contained Hugo site in `/exampleSite/`, but note that for security reasons the content directory on the Hugo showcase will still be published from the [Hugo Basic Example](https://github.com/gohugoio/hugoBasicExample/tree/master/content) repository.

Thusly, I would not consider this issue a *wont-fix* case

**Comment by VincentTam** [comment]
> 1. There are post duplicates

@onweru Refer to item 3 in https://github.com/gohugoio/hugoThemes/issues/665#issuecomment-517635357.

**Comment by onweru** [comment]
> > 1. There are post duplicates
> 
> @onweru Refer to item 3 in [gohugoio/hugoThemes#665 (comment)](https://github.com/gohugoio/hugoThemes/issues/665#issuecomment-517635357).

It seems that this issue disappeared overnight

**Comment by VincentTam** [comment]
@onweru Thanks for update.
