### ISSUE TITLE
Staticman comment display error

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#4]
Steps to reproduce the error:

1. `git fetch upstream master`
2. `git checkout upstream/master`
3. Edit `config.toml` and set `staticman` to `true`
4. `cd exampleSite` and `hugo serve --themesDir=../..`

Error obtained:

```
Building sites … WARN 2019/05/19 10:13:33 Data for key 'name' in path 'hugo-swift-theme/designer.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:13:33 Data for key 'url' in path 'hugo-swift-theme/designer.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:13:33 The []interface {} data from 'hugo-swift-theme/menu.yml' overridden by higher precedence []interface {} data already in the data tree
WARN 2019/05/19 10:13:33 Data for key 'branch' in path 'hugo-swift-theme/staticman.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:13:33 Data for key 'username' in path 'hugo-swift-theme/staticman.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:13:33 Data for key 'repository' in path 'hugo-swift-theme/staticman.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:13:33 Data for key 'endpoint' in path 'hugo-swift-theme/staticman.yml' is overridden by higher precedence data already in the data tree
WARN 2019/05/19 10:13:33 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
ERROR 2019/05/19 10:13:33 render of "page" failed: execute of template failed: template: _default/single.html:19:44: executing "main" at <partial "comments.html" .>: error calling partial: "/home/vin100/hugo-swift-theme/layouts/partials/comments.html:3:18": execute of template failed: template: partials/comments.html:3:18: executing "partials/comments.html" at <readDir "data/comments">: error calling readDir: failed to read directory "data/comments": open /home/vin100/hugo-swift-theme/exampleSite/data/comments: no such file or directory
ERROR 2019/05/19 10:13:33 render of "page" failed: execute of template failed: template: _default/single.html:19:44: executing "main" at <partial "comments.html" .>: error calling partial: "/home/vin100/hugo-swift-theme/layouts/partials/comments.html:3:18": execute of template failed: template: partials/comments.html:3:18: executing "partials/comments.html" at <readDir "data/comments">: error calling readDir: failed to read directory "data/comments": open /home/vin100/hugo-swift-theme/exampleSite/data/comments: no such file or directory
ERROR 2019/05/19 10:13:33 render of "page" failed: execute of template failed: template: _default/single.html:19:44: executing "main" at <partial "comments.html" .>: error calling partial: "/home/vin100/hugo-swift-theme/layouts/partials/comments.html:3:18": execute of template failed: template: partials/comments.html:3:18: executing "partials/comments.html" at <readDir "data/comments">: error calling readDir: failed to read directory "data/comments": open /home/vin100/hugo-swift-theme/exampleSite/data/comments: no such file or directory
ERROR 2019/05/19 10:13:33 render of "page" failed: execute of template failed: template: _default/single.html:19:44: executing "main" at <partial "comments.html" .>: error calling partial: "/home/vin100/hugo-swift-theme/layouts/partials/comments.html:3:18": execute of template failed: template: partials/comments.html:3:18: executing "partials/comments.html" at <readDir "data/comments">: error calling readDir: failed to read directory "data/comments": open /home/vin100/hugo-swift-theme/exampleSite/data/comments: no such file or directory
Total in 50 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:19:44: executing "main" at <partial "comments.html" .>: error calling partial: "/home/vin100/hugo-swift-theme/layouts/partials/comments.html:3:18": execute of template failed: template: partials/comments.html:3:18: executing "partials/comments.html" at <readDir "data/comments">: error calling readDir: failed to read directory "data/comments": open /home/vin100/hugo-swift-theme/exampleSite/data/comments: no such file or directory
```

Cause for this error: newly created site has _no_ comments, so the `readDir` in your `layout/partials/comments.html` throws an error.  You may take, for example, a look at [Beautiful Hugo's partial layout](https://github.com/halogenica/beautifulhugo/blob/07f765675dab2b00ad39aa460118edff2f2d3fcd/layouts/partials/staticman-comments.html#L3-L34) to solve this problem.

**Comment by VincentTam** [comment]
In order to circumvent this error and show you another error, I created an empty repo `data/comments`, and ran the previous `hugo server ...` command again, and _no_ HTML comment form was shown.

![Sample output w/o form](http://i.imgur.com/XrzF6pM.png)  
Image link: http://i.imgur.com/XrzF6pM.png

**Comment by onweru** [comment]
@VincentTam, kindly bear with me I haven't had the time to update things here. Hugo will throw an error if there are no comments on the data directory. I'll try to allocate some time to that bug.

Now, manually creating a comments directory won't show any comments on the html. Here is an idea of how the final comments yams file look like (see screenshot)
<img width="1280" alt="Screen Shot 2019-05-19 at 5 20 42 PM" src="https://user-images.githubusercontent.com/16350351/57983446-9fe8f300-7a5a-11e9-9b9a-1c0838265921.png">

**Comment by VincentTam** [comment]
> Now, manually creating a comments directory won't show any comments on the html.

That's a workaround, but I can reluctantly say that's a solution.  Wrapping the whole thing with Hugo's built-in `{{ if .Site.Data.comments }}` is more elegant than cluttering the repo with a manually created `data/comments/.gitkeep` (note that empty repo _can't_ be indexed) due to some users who prefer _not_ using Staticman.  You may see, for example, the partial layouts of the themes [Beautiful Hugo](https://github.com/halogenica/beautifulhugo/blob/07f765675dab2b00ad39aa460118edff2f2d3fcd/layouts/partials/staticman-comments.html#L3-L34) and [Minimo](https://github.com/MunifTanjim/minimo/blob/c8967699cc68d3e3ccf7981e6b224ab910c198d9/layouts/partials/comments/staticman/list.html).

**Comment by onweru** [comment]
Good point. The suggestion is implemented in the commit https://github.com/onweru/hugo-swift-theme/commit/2395dd42cedb87f3f11bb1609ab2c1dbfb7cfb9c

**Comment by VincentTam** [comment]
Unluckily the problem is still there.

![screen shot](https://i.imgur.com/cnEUj8Z.png)
Image URL: https://imgur.com/cnEUj8Z

Note the position (3:18) of the above error listing.

https://github.com/onweru/hugo-swift-theme/blob/2395dd42cedb87f3f11bb1609ab2c1dbfb7cfb9c/layouts/partials/comments.html#L1-L5

https://github.com/onweru/hugo-swift-theme/commit/2395dd42cedb87f3f11bb1609ab2c1dbfb7cfb9c#diff-4bc063bcdcf2e635a36bd0d8d6273ad8 changes outer parts instead.  I'm going to propose some changes in a separate PR.

**Comment by VincentTam** [comment]
> In order to circumvent this error and show you another error, I created an empty repo `data/comments`, and ran the previous `hugo server ...` command again, and _no_ HTML comment form was shown.
> 
> ![Sample output w/o form](http://i.imgur.com/XrzF6pM.png)
> Image link: http://i.imgur.com/XrzF6pM.png

In fact, I've missed a slash while setting up my sample site on Framagit.  That had broken the links of some JavaScripts.  After adding it back, the form
