### ISSUE TITLE
Adding author profile to posts

### ISSUE THREAD

**Issue by siddhugolu** [onweru/hugo-swift-theme#53]
Loving the layout of the theme! I was trying to add the "Written by" block to posts, but couldn't figure out how to. I have copied authors.yml to my Data directory. What other changes do I need to do to make it work?

**Comment by siddhugolu** [comment]
Adding a screenshot from your website for the reference to what I had in mind
![image](https://user-images.githubusercontent.com/9106868/65390343-6e22c880-dd7b-11e9-9d44-f047e2cbd992.png)

**Comment by onweru** [comment]
@siddhugolu, 

> Loving the layout of the theme!

Awesome.  Thanks for the feedback. Happy to know you find useful

>  I was trying to add the "Written by" block to posts, but couldn't figure out how to. I have copied authors.yml to my Data directory. What other changes do I need to do to make it work?

I realized this aspect wasn't properly documented; my bad. I added a README [section here](https://github.com/onweru/hugo-swift-theme#written-by-block).

I also updated the `exampleSite/data/authors.yml` file to include the right files.

Let me know if it works for you.

**Comment by VincentTam** [comment]
> I was trying to add the "Written by" block to posts

Note that all visible elements in the theme are supposed to have a translation.  I've already translated "written by" into two other languages (French and Chinese).  This is used in `layouts/partials/author.html`.

**Comment by siddhugolu** [comment]
@onweru Thanks, that worked like a charm!
