### ISSUE TITLE
Bullets in list don't show up

### ISSUE THREAD

**Issue by pgrandinetti** [onweru/hugo-swift-theme#55]
Code:

```
This is a list
  - A
  - B
```
Result is in the attached figure.
I tried with indentation set to 4 spaces, but in that case it produces a black block of code (which is also very strange, imho).
I tried without indentation too, and the result is the same

![Screenshot from 2019-10-02 11-23-14](https://user-images.githubusercontent.com/10454135/66033232-23d1e200-e507-11e9-9ef6-0f383d392b06.png)

**Comment by VincentTam** [comment]
> Code:
> 
> ```
> This is a list
>   - A
>   - B
> ```

What about inserting a blank line before the 1st item?

**Comment by pgrandinetti** [comment]
tried that too (I forgot to mention). Same result.
Can you reproduce it? I am using Google Chrome 77.0.3865.90 on Ubuntu 16.04.6 LTS
