### ISSUE TITLE
Hidden page option

### ISSUE THREAD

**Issue by kvandenbrande** [onweru/hugo-swift-theme#57]
I would like to migrate from an other theme, where I use in front matter the hidden function to prevent it from showing up between the other posts, just want it to show in my menu. 
How can I hide it with this theme? 
`+++
title = "Contact"
hidden = "true"
+++`

**Comment by onweru** [comment]
@kvandenbrande, the use case you described above isn’t immediately clear. Could you provide more information or clarify further?

**Comment by kvandenbrande** [comment]
In the \content\post\ folder I have all my blog posts -> perfect 
In the \content\  I got several pages (like contact page) which are accessible from my menu but the issue is that they also show up between my blog posts. My question is now how can I prevent that?

**Comment by onweru** [comment]
Aha, I will add a filter for that in the next day or two. Thanks for pointing that out.

**Comment by onweru** [comment]
@kvandenbrande, [edit this line](https://github.com/onweru/hugo-swift-theme/blob/de9ba6ceb50c6cfdf7d1ddfa8d8f8e1f8f052968/exampleSite/config.toml#L21) in your config file accordingly.

To elaborate,  if your blog resides inside a folder called __posts__, you would edit the line I referenced above to look like:

```yaml
...
blogDir = "posts"
...
```

closing this within the next couple of days.

**Comment by GaProgMan** [comment]
I'm still seeing this issue, but have a fix. PR incoming.
