### ISSUE TITLE
Author block not working

### ISSUE THREAD

**Issue by billhennessy** [onweru/hugo-swift-theme#60]
Repro:
1. Copy data.authors.yaml to data folder
2. add `author: "yourName"` to a post
3. rebuild

Expected:
Default author block appears in post
Actual:
No author block in post

Versions:
Hugo 0.67.1
Swift 0.42

**Comment by onweru** [comment]
@billhennessy, ensure that the values of __1__ & __2__ below 👇 match

1. `author` in your post i.e content/blogFolder/name-of-post.md
2. `name` in data/authors.yaml

```
# in your authors yaml file
name: "Bill"
...
# in your post
author: "Bill"
```
The data file helps you an authors information only once.

If this doesn't work for you, I could have a look at your code.

**Comment by andresf91** [comment]
Hi.

I've had mixed results with this feature too:
If you define the author's name in data/authors.yaml with uppercase, it fails. e.g. `name: "Bill"` doesn't work for me, but `name: "Bill"` does

Versions:
hugo 0.69.1
swift 0.42

**Comment by onweru** [comment]
Thanks for that observation. I will do something about case sensitivity

**Comment by billhennessy** [comment]
Shifting everything to lower case worked. Thanks.

**Comment by onweru** [comment]
@billhennessy, @andresf91 

If you find the time, kindly let me know if this now works for you too irrespective of the case.

**Comment by billhennessy** [comment]
@onweru, one additional issue: even though the author yaml has a photo index, it seems the code ignores this and looks for "firstname%20lastname.jgp"

**Comment by billhennessy** [comment]
It looks case insensitive now, though. Thanks, @onweru  and @andresf91

**Comment by onweru** [comment]
> @onweru, one additional issue: even though the author yaml has a photo index, it seems the code ignores this and looks for "firstname%20lastname.jgp"

I will look into this @billhennessy

**Comment by andresf91** [comment]
Thanks for the fix.
I really should reword my previous comment, since I started writing that I had had "mixed results", because I thought that I couldn't set authors' names with non-English characters. But I tried again before sending the comment and suddenly it was working.
But I should have removed the "mixed results" part, because it wasn't so serious.

**Comment by onweru** [comment]
> @onweru, one additional issue: even though the author yaml has a photo index, it seems the code ignores this and looks for "firstname%20lastname.jgp"

fixed.
