### ISSUE TITLE
Tags pages not working

### ISSUE THREAD

**Issue by GabMus** [onweru/hugo-swift-theme#61]
Tag pages should be automatically generated, showing articles with the same tag (ie: if I go to /tags/development I should see all posts tagged development)

Tag pages show all articles, without any filtering by tag

Here's a video showing the problem (note that I have modified the theme quite a bit): <https://streamable.com/8spw7x>

**Comment by onweru** [comment]
@GabMus,

I would probably need to see your setup.

Ensure you haven't disabled tags from you `config` file though

**Comment by GabMus** [comment]
Sure, feel free to take a look: https://gitlab.com/gabmus/techpills-website

**Comment by onweru** [comment]
@GabMus,
 
> Tag pages should be automatically generated, __showing articles with the same tag__ (ie: if I go to /tags/development I should see all posts tagged development)

Upon further examination, I can confirm that tags pages on your website are actually showing articles __with the same tag__. The reason you get the impression that they do not is because the tag label on the article cards only show the first tag in a list of cards.

Put differently, if you have an article that has 3 tags i.e `tags = ["plymouth", "dev", "pills"]` that article will be listed on _yourDomain/tags/dev_ but its card will have a tag link of "plymouth".

That's kinda disturbing. I will fix it.

> Tag pages show all articles, without any filtering by tag

Filtering exists. It's the labelling that's misleading.

**Comment by onweru** [comment]
> @GabMus,
> 
> > Tag pages should be automatically generated, **showing articles with the same tag** (ie: if I go to /tags/development I should see all posts tagged development)
> 
> Upon further examination, I can confirm that tags pages on your website are actually showing articles **with the same tag**. The reason you get the impression that they do not is because the tag label on the article cards only show the first tag in a list of cards.
> 
> Put differently, if you have an article that has 3 tags i.e `tags = ["plymouth", "dev", "pills"]` that article will be listed on _yourDomain/tags/dev_ but its card will have a tag link of "plymouth".
> 
> That's kinda disturbing. I will fix it.
> 
> > Tag pages show all articles, without any filtering by tag
> 
> Filtering exists. It's the labelling that's misleading.

Ignore this 👆. That's not the issue. comment out [line 26 on your config file](https://gitlab.com/gabmus/techpills-website/-/blob/master/config.toml#L26) or delete it and your posts ought to work as intended.

**Comment by GabMus** [comment]
Yeah, commenting out that line it works, but it also shows non post pages like about and community in the homepage

**Comment by GabMus** [comment]
> Your choice of colors is neat +1 +1

Thanks! But can't take full credit for it, it's based on the [GNOME HIG palette](https://developer.gnome.org/hig/stable/icon-design.html.en)

**Comment by GabMus** [comment]
Sorry but I just realized that maybe I wasn't clear: if I comment out line 26 as you suggested, the tags work properly, but I can also see non-blog pages (community, about) in the homepage (which should contain the blog articles only). I'd want to hide those pages from the home page, as they're hidden in other themes.

Is this off-topic for this issue? Should I open a new one? Thanks a lot.

**Comment by onweru** [comment]
@GabMus i got your point the first time. I’ll hv dig in when I got time. Thanks for identifying the buggy behavior 😉

**Comment by GabMus** [comment]
Sure, no problem! And thanks for making this awesome theme! :grinning:

**Comment by onweru** [comment]
> @GabMus,
> 
> Comment out [line 26 on your config file](https://gitlab.com/gabmus/techpills-website/-/blob/master/config.toml#L26) or delete it and your posts ought to work as intended.

@GabMus 

This is no longer applicable. you can now specify a `blogDir` in your config and all the tags pages should work as intended.

Let me know if this works for you.

**Comment by GabMus** [comment]
Alright, tags work as expected now. But there is a new error (that I managed to work around by surrounding everything in `layout/partials/author.html` with `{{ if isset .Site.Data "authors" }} <!-- actual content of author --> {{ end }}`).

Here's the error without my workaround:

```
Building sites … ERROR 2020/05/08 17:50:16 render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
ERROR 2020/05/08 17:50:16 render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
ERROR 2020/05/08 17:50:16 render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
ERROR 2020/05/08 17:50:16 render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
Built in 55 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
```

Anyway, thanks a lot for fixing the issue with tags!

**Comment by onweru** [comment]
> Alright, tags work as expected now. But there is a new error (that I managed to work around by surrounding everything in `layout/partials/author.html` with `{{ if isset .Site.Data "authors" }} <!-- actual content of author --> {{ end }}`).
> 
> Here's the error without my workaround:
> 
> ```
> Building sites … ERROR 2020/05/08 17:50:16 render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
> ERROR 2020/05/08 17:50:16 render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
> ERROR 2020/05/08 17:50:16 render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
> ERROR 2020/05/08 17:50:16 render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
> Built in 55 ms
> Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:19:8: executing "main" at <partial "author" .>: error calling partial: "/home/gabmus/git/techpillshugo/themes/hugo-swift-gabmus-theme/layouts/partials/author.html:1:22": execute of template failed: template: partials/author.html:1:22: executing "partials/author.html" at <where .Site.Data.authors (lower "name") (lower .Params.author)>: error calling where: can't iterate over <nil>
> ```
> 
> Anyway, thanks a lot for fixing the issue with tags!

@GabMus 

Thanks for identifying those bugs. If you may check if the latest commit works without your workaround.

**Comment by GabMus** [comment]
Alright, with the latest commit everything seems to be working! Thanks for taking the time to fix these bugs, keep it up!
