### ISSUE TITLE
Link sharing issue

### ISSUE THREAD

**Issue by s-azizoglu** [onweru/hugo-swift-theme#63]
In any number of pages, when we copy post's links with "Share Story" button, it copies current page's link, not the directed post's link.

**Comment by s-azizoglu** [comment]
Now it copies only page URL but domain is not included that URL. 
Even I write in config.toml as a baseurl my domain. 
For instance;
Article's URL is on my server: [example.com/article.html]
When I use that copier, it only copy [/article.html]
Thanks.

**Comment by onweru** [comment]
Umh, this demo site uses the same theme https://neuralvibes.com/ ... doesn’t seem to have that issue

**Comment by s-azizoglu** [comment]
I couldn't find the issue. Even I tried on Ubuntu OS with clean installation, it did not work. 
If you don't mind, could you share your https://neuralvibes.com's project file. If you don't, no problem. I thank you still your effort for creating that theme. 
Thanks Dan Weru!

**Comment by onweru** [comment]
@s-azizoglu,

It's done. Let me know if you can place your finger on the problem
