### ISSUE TITLE
Border issue in page navigator

### ISSUE THREAD

**Issue by siddhugolu** [onweru/hugo-swift-theme#64]
Hi, In the bottom pagination sector, I'm seeing a weird border on the right and downside. Attaching a picture for your reference:

![image](https://user-images.githubusercontent.com/9106868/83380511-b8287780-a3fb-11ea-97d2-f91fcf51507b.png)

Since the pagination sector is never going to be scrollable, can anything be done to get rid of these borders?

**Comment by s-azizoglu** [comment]
I've solved that issue with a changing in **_posts.sass** file.
This file is in assets/sass folder.
In that file you can change pager's overflow to auto and it will be gone;
`.pager
overflow: auto
`

![image](https://user-images.githubusercontent.com/42344964/83785683-5afe2180-a69a-11ea-826e-2d7b731e7b69.png)

**Comment by siddhugolu** [comment]
@s-azizoglu Thanks a lot, that solves the issue :)
