### ISSUE TITLE
4th Page in navigator not working

### ISSUE THREAD

**Issue by siddhugolu** [onweru/hugo-swift-theme#66]
Hi, in the pagination sector, the 4th button is greyed out and the button doesn't work. However, the next page button is working as expected. Here's the screenshot:

![image](https://user-images.githubusercontent.com/9106868/84147094-70989000-aa7a-11ea-9ae5-d1aef7547dd3.png)

**Comment by s-azizoglu** [comment]
It is not an issue actually. It designed as it is. What I'm saying is that when you click 3rd page, then after it opened, 4th page will be clickable.

**Comment by siddhugolu** [comment]
I see. So I assume the intent is to, aesthetically, make two greyed out buttons on each side of the middle button, something like this:

![image](https://user-images.githubusercontent.com/9106868/84584419-bf02b180-ae21-11ea-8b48-12116db0f1e3.png)

It just seemed strange that only one of the buttons was unclickable at any given point. Thank you for the clarification.
