### ISSUE TITLE
Site name display problem

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#7]
The background of the site header overlaps with the site name at the top left-hand corner if the site name is too long.

![Screenshot_2019-06-04 Swift + Staticman + Framagit](https://user-images.githubusercontent.com/5748535/58916164-1d7f5500-8723-11e9-9c68-e9bfa317173a.png)
Sample screenshot illustrating the error.

**Comment by onweru** [comment]
@VincentTam, thanks for noticing the bug. Originally the theme was developed for personal use; I had set what would be the `logo` element as a fixed width element. I will rectify this asap.

**Comment by onweru** [comment]
fixed 😀

**Comment by VincentTam** [comment]
Thanks for your fix!  Now it's working great!
