### ISSUE TITLE
youtube video instead image

### ISSUE THREAD

**Issue by anibal-aguila** [onweru/hugo-swift-theme#74]
Hi, there are some way to substitute the cover image with youtube video code on the main site and into the post?

![image](https://user-images.githubusercontent.com/49025536/128226613-58ffed8b-f546-4248-825c-d3945ef96fe4.png)

thanks in advance,

**Comment by onweru** [comment]
@anibal-aguila, that's an interesting idea. I think it's possible, at least on the post.
