### ISSUE TITLE
How to change the main page header?

### ISSUE THREAD

**Issue by bksubhuti** [onweru/hugo-swift-theme#75]
I like this theme.  I just want to change the main page header image..   It has this black thing and audio script .
I tried many things like adding  _index.md .
That will change the title of the inner div but cannot change the picture.
I want to have my own image.

Am I missing something.?

**Comment by icifra** [comment]
Do you happen to know how to contact the developer?

**Comment by onweru** [comment]
@bksubhuti, still need help?
