### ISSUE TITLE
[Bug?] Lack of integrity

### ISSUE THREAD

**Issue by VincentTam** [onweru/hugo-swift-theme#8]
https://github.com/onweru/hugo-swift-theme/blob/bcd5841aca92e048d0164e7db2e75864a37a262b/layouts/partials/head.html#L20

The above line is supposed to show the `integrity` of the main CSS.  Nonetheless, in the HTML source of the generated page on the official demo https://neuralvibes.com/, the `integrity` is left blank.  Is it the intended behaviour?

I'm using Xubuntu 18.04 Firefox and qutebrowser, but I suppose that this is cross-platform.

**Comment by onweru** [comment]
Thanks for pointing that out @VincentTam, I had overlooked that. It's now fixed.

**Comment by onweru** [comment]
For context, the *integrity* attribute is used for [asset fingerprinting](https://discourse.gohugo.io/t/please-explain-fingerprinting-for-static-websites-to-me/16771)

**Comment by VincentTam** [comment]
Thanks for your fix @onweru.
